### ISSUE TITLE
duckdb 0.9

### ISSUE THREAD

**Issue by JasonMuteham** [AlexR2D2/metabase_duckdb_driver#17]
Hi,

Is there an update in the pipeline?

**Comment by AlexR2D2** [comment]
Hi, 0.9.0 is preview release, let's wait until release (0.9.1)

**Comment by JasonMuteham** [comment]
Ok, however, Motherduck is planning to upgrade on the 10th October.

https://motherduck.com/docs/key-tasks/upgrading-to-DuckDB-0.9

**Comment by AlexR2D2** [comment]
Updated up to 0.9.1
