### ISSUE TITLE
Cannot filter date values with 0.10.0 update

### ISSUE THREAD

**Issue by nfire11** [AlexR2D2/metabase_duckdb_driver#24]
I updated the driver to 0.10.0, but met some error in filtering datetime values.
I have checked sql script auto-generated by metabase when applying a date filter :

`where datetime >= timestamp with time zone '2023-01-01 00:00:00.000Z'  `

It works fine in 0.9.1 but would return an error which asks for a type conversion in 0.10.0
If mannually change the type to timestamp without timezone, it works.
`where datetime >= timestamp without time zone '2023-01-01 00:00:00.000Z'  `

Any idea about fixing that?

**Comment by AlexR2D2** [comment]
Hmm... i tried it in the Met abase 1.48.7 with 0.10.0, it seems that both variants work
<img width="1140" alt="Screenshot 2024-03-05 at 00 09 45" src="https://github.com/AlexR2D2/metabase_duckdb_driver/assets/31543570/7a6e5067-c39f-4686-a5a1-7199d68c3218">

**Comment by nfire11** [comment]
Hi Alex! Nice work for developing the driver.
It will happen when you apply a datetime filter.
![image](https://github.com/AlexR2D2/metabase_duckdb_driver/assets/4922179/a25409b1-04a6-405d-8bd3-889d9f09fa50)

Which requires an explicit type conversion for datetime comparisions (timestamp without time zone VS timestamp with time zone) 
This might be a feature in duckdb 0.10? I complied the driver with duckdb 0.9.2 works..

script generated when applying a filter:
``` WHERE
  (
    "public"."gset"."ndt_datetime" >= timestamp with time zone '2024-01-01 00:00:00.000+08:00'
  )
 
   AND (
    "public"."gset"."ndt_datetime" < timestamp with time zone '2024-03-06 00:00:00.000+08:00'
  ) ```

**Comment by nfire11** [comment]
> I did some testing and this can be fixed by setting `SET old_implicit_casting = true;`. Would this be possible at driver level? If so would it be possible to add some other configurations too from environment variables?

Thanks, Roope. I complied the 0.10.0 driver with the settings. It works! You can put extra configuration variables in the plugin source code.
Maybe it would be helpful to add an optional field in the plugin to set connection properties?

**Comment by AlexR2D2** [comment]
Hi, as lib maintainer I can't make decisions for the developer do you need the `old_implicit_casting` as `true` or `false`, so i added the settings on db settings page
