### ISSUE TITLE
How to connect 'motherduck'  database 

### ISSUE THREAD

**Issue by coderyeasin** [AlexR2D2/metabase_duckdb_driver#27]

**Comment by coderyeasin** [comment]
Previous issues was resolved! so that's why closed.

I want to connect with 'motherduck' using this driver can i do that?

**Comment by vgrimaldi848** [comment]
You will need the 0.9.2 release of the jdbc driver to connect to Motherduck. 

You will just need to setup the correct jdbc url according to:

https://motherduck.com/docs/integrations/dbeaver/

as you would connect with a normal JDBC client.

**Comment by coderyeasin** [comment]
@vgrimaldi848 Thnak you so much your response! it was version conflicts and resolve with this version.

**Comment by coderyeasin** [comment]
@vgrimaldi848 using this dbeaver successfully created connection with my motherduck database and i can see tables, can query as well as other stuff too.

according to this metabase-duckdb-driver  requirement i'm successfully installed .jar file into /home/plugins folder and set .env using docker in ubuntu

**Point is**: so my point is how would i connect this motherduck database into metabase so that i can visualize data.

because i created several connection but its saved as blanked database, i'm provide 'duckdb' setup options in metabase please see my attached image, configuration is same according to this driver requirement but what i'm missing can't resolve yet.

@AlexR2D2 Can you please look into this.

![Screenshot from 2024-03-13 01-23-08](https://github.com/AlexR2D2/metabase_duckdb_driver/assets/33999408/995c6f95-8cf4-4c49-a617-96912c8c429a)

**Comment by coderyeasin** [comment]
I am downgrade and upgrade but its not compatible so can't see any 'DuckDB to 0.9.2' in this driver versions, for above solution to connect motherduck using jdbc driver its successfully worked but can't integrate with metabase? 

![Screenshot from 2024-03-14 16-47-02](https://github.com/AlexR2D2/metabase_duckdb_driver/assets/33999408/2b54a34b-e9a2-4b86-8720-05420d79a982)
