### ISSUE TITLE
Upgarde duckdb client to 0.6.0

### ISSUE THREAD

**Issue by billmetangmo** [AlexR2D2/metabase_duckdb_driver#6]
Hello,

Thanks for sharing this work with community.
I got this issue:
`IO Error: Failed to download extension "sqlite" at URL "http://extensions.duckdb.org/v0.5.1/linux_amd64/sqlite.duckdb_extension.gz" Candidate extensions: "icu", "fts"` when trying to load/install sqlite scanner from metabase query console.

This seems to be related to the version of the extension which 0.5.1 instead of 0.6.0.

Regards

**Comment by igitur** [comment]
v0.6.1 has been released, which contains the fix you mention. https://github.com/duckdb/duckdb/releases/tag/v0.6.1

(Thanks for this plugin!)

**Comment by AlexR2D2** [comment]
> v0.6.1 has been released, which contains the fix you mention. https://github.com/duckdb/duckdb/releases/tag/v0.6.1

Upgraded.

**Comment by igitur** [comment]
Sorry, currently on holiday. Will test and give feedback mid January.
